msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2024-08-18 09:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI +ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"Language-Code: en\n"
"Language-Name: English\n"
"Preferred-Encodings: utf-8 latin1\n"
"Domain: DOMAIN\n"

#: ../validators/IdValidator.py:26
msgid "Id $id is already in use"
msgstr "$id kimliği zaten kullanılıyor"

#: ../validators/IdValidator.py:17
msgid "Spaces are not allowed in ids"
msgstr "Kimliklerde boşluğa izin yok"

#: ../validators/RegexValidator.py:46
msgid "Validation failed($name): $value of type $type, expected 'string'"
msgstr "Denetim başarısız oldu($name): $value $type değil 'string' tipinden olmalıydı"

#: ../validators/RegexValidator.py:65
msgid "Validation failed($name): '$value' $errmsg"
msgstr "Denetim başarısız oldu($name): '$value' $errmsg"

#: ../validators/EmptyValidator.py:45
msgid "Validation failed($name): '$value' is not empty."
msgstr "Denetim başarısız oldu($name): '$value' boş değil."

#: ../validators/RangeValidator.py:41
msgid "Validation failed($name): '$value' out of range($min, $max)"
msgstr "Denetim başarısız oldu($name): '$value' ($min, $max) aralığında değil."

#: ../validators/SupplValidators.py:103
msgid "Validation failed($name): could not convert $value to a date."
msgstr "Denetim başarısız oldu($name): $value bir tarih değerine çevrilemedi."

#: ../validators/RangeValidator.py:33
msgid "Validation failed($name): could not convert '$value' to number"
msgstr "Denetim başarısız oldu($name): '$value' bir sayı değerine çevrilemedi."

#: ../validators/SupplValidators.py:94
msgid "Validation failed($name): value is empty ($value)."
msgstr "Denetim başarısız oldu($name): '$value' boş."

#: ../validators/SupplValidators.py:71
msgid "Validation failed($name: Uploaded data is too large: ${size}MB (max ${max}MB)"
msgstr "Denetim başarısız oldu($name: Yüklenen veri çok büyük: ${size}MB (en fazla ${max}MB)"

#: ../validators/BaseValidators.py:51
msgid "contains unprintable characters"
msgstr "içinde basılamaz karakterler var"

#: ../validators/BaseValidators.py:37
msgid "is not a decimal number."
msgstr "ondalık bir sayı değil."

#: ../validators/BaseValidators.py:95
msgid "is not a valid email address."
msgstr "geçerli bir e-posta adresi değil."

#: ../validators/BaseValidators.py:74
msgid "is not a valid international phone number."
msgstr "geçerli bir uluslararası telefon numarası değil."

#: ../validators/BaseValidators.py:88
msgid "is not a valid url."
msgstr "geçerli bir URL adresi değil."

#: ../validators/BaseValidators.py:66
msgid "is not a valid us phone number."
msgstr "geçerli bir ABD telefon numarası değil."

#: ../validators/BaseValidators.py:81
msgid "is not a valid zip code."
msgstr "geçerli bir posta kodu değil."

#: ../validators/BaseValidators.py:58
msgid "is not a well formed SSN."
msgstr "geçerli bir SSN (sosyal güvenlik numarası) değil."

#: ../validators/BaseValidators.py:44
msgid "is not an integer."
msgstr "bir tam sayı değil."

#: ../validators/BaseValidators.py:109
msgid "this name is not a valid identifier"
msgstr "bu isim geçerli bir kimlik değil"

#: ../validators/ExpressionValidator.py:94
msgid "validation failed, expr was:$expr"
msgstr "denetim başarısız oldu, expr:$expr"
