msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2024-08-18 09:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI +ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"Language-Code: en\n"
"Language-Name: English\n"
"Preferred-Encodings: utf-8 latin1\n"
"Domain: DOMAIN\n"

#: ../validators/IdValidator.py:26
msgid "Id $id is already in use"
msgstr "ID $id はすでに使われています"

#: ../validators/IdValidator.py:17
msgid "Spaces are not allowed in ids"
msgstr "ID内にスペースは許されません"

#: ../validators/RegexValidator.py:46
msgid "Validation failed($name): $value of type $type, expected 'string'"
msgstr "バリデーション失敗($name): $type タイプの値 $value は 'string' が期待されます"

#: ../validators/RegexValidator.py:65
msgid "Validation failed($name): '$value' $errmsg"
msgstr "バリデーション失敗($name): '$value' $errmsg"

#: ../validators/EmptyValidator.py:45
msgid "Validation failed($name): '$value' is not empty."
msgstr "バリデーション失敗($name): 値 '$value' が空ではありません"

#: ../validators/RangeValidator.py:41
msgid "Validation failed($name): '$value' out of range($min, $max)"
msgstr "バリデーション失敗($name): 値 '$value' は ($min, $max) の範囲外です"

#: ../validators/SupplValidators.py:103
msgid "Validation failed($name): could not convert $value to a date."
msgstr "バリデーション失敗($name): 値 $value を日付に変換できません"

#: ../validators/RangeValidator.py:33
msgid "Validation failed($name): could not convert '$value' to number"
msgstr "バリデーション失敗($name): 値 '$value' を数値に変換できません"

#: ../validators/SupplValidators.py:94
msgid "Validation failed($name): value is empty ($value)."
msgstr "バリデーション失敗($name): 値が空です ($value)."

#: ../validators/SupplValidators.py:71
msgid "Validation failed($name: Uploaded data is too large: ${size}MB (max ${max}MB)"
msgstr "バリデーション失敗($name: アップロードされたデータが大きすぎます: ${size}MB (max ${max}MB)"

#: ../validators/BaseValidators.py:51
msgid "contains unprintable characters"
msgstr "プリントできない文字を含んでいます"

#: ../validators/BaseValidators.py:37
msgid "is not a decimal number."
msgstr "十進数ではありません"

#: ../validators/BaseValidators.py:95
msgid "is not a valid email address."
msgstr "有効なメールアドレスではありません"

#: ../validators/BaseValidators.py:74
msgid "is not a valid international phone number."
msgstr "有効な国際電話番号ではありません"

#: ../validators/BaseValidators.py:88
msgid "is not a valid url."
msgstr "有効なURLではありません"

#: ../validators/BaseValidators.py:66
msgid "is not a valid us phone number."
msgstr "有効なUS 電話番号ではありません"

#: ../validators/BaseValidators.py:81
msgid "is not a valid zip code."
msgstr "有効なUS ZIPコードではありません"

#: ../validators/BaseValidators.py:58
msgid "is not a well formed SSN."
msgstr "適格な US SSN ではありません"

#: ../validators/BaseValidators.py:44
msgid "is not an integer."
msgstr "整数ではありません"

#: ../validators/BaseValidators.py:109
msgid "this name is not a valid identifier"
msgstr "この名前は有効な識別子ではありません"

#: ../validators/ExpressionValidator.py:94
msgid "validation failed, expr was:$expr"
msgstr "バリデーションに失敗しました。exprは次のものです: $expr"
