msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2024-08-18 09:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI +ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"Language-Code: en\n"
"Language-Name: English\n"
"Preferred-Encodings: utf-8 latin1\n"
"Domain: DOMAIN\n"

#: ../validators/IdValidator.py:26
msgid "Id $id is already in use"
msgstr "Tunniste $id on jo käytössä"

#: ../validators/IdValidator.py:17
msgid "Spaces are not allowed in ids"
msgstr "Välilyönnit eivät ole sallittu tunnisteissa"

#: ../validators/RegexValidator.py:46
msgid "Validation failed($name): $value of type $type, expected 'string'"
msgstr "Validointi epäonnistui($name): tyypin $type arvo $value, odotettiin merkkijonoa"

#: ../validators/RegexValidator.py:65
msgid "Validation failed($name): '$value' $errmsg"
msgstr "Validointi epäonnistui($name): '$value' $errmsg"

#: ../validators/EmptyValidator.py:45
msgid "Validation failed($name): '$value' is not empty."
msgstr "Validointi epäonnistui($name): '$value' ei ole tyhjä."

#: ../validators/RangeValidator.py:41
msgid "Validation failed($name): '$value' out of range($min, $max)"
msgstr "Validointi epäonnistui($name): '$value' raja-arvojen ulkopuolella ($min, $max)"

#: ../validators/SupplValidators.py:103
msgid "Validation failed($name): could not convert $value to a date."
msgstr "Validointi epäonnistui($name): ei voi kääntää $value päivämääräksi."

#: ../validators/RangeValidator.py:33
msgid "Validation failed($name): could not convert '$value' to number"
msgstr "Validointi epäonnistui($name): ei voinut kääntää '$value' numeroksi"

#: ../validators/SupplValidators.py:94
msgid "Validation failed($name): value is empty ($value)."
msgstr "Validointi epäonnistui($name): value on tyhjä ($value)."

#: ../validators/SupplValidators.py:71
msgid "Validation failed($name: Uploaded data is too large: ${size}MB (max ${max}MB)"
msgstr "Validointi epäonnistui($name): palvelimelle kopioitu tiedosto on liian suuri: ${size}MB (max ${max}MB)"

#: ../validators/BaseValidators.py:51
msgid "contains unprintable characters"
msgstr "sisältää tulostuskelvottomia merkkejä"

#: ../validators/BaseValidators.py:37
msgid "is not a decimal number."
msgstr "ei ole murtoluku."

#: ../validators/BaseValidators.py:95
msgid "is not a valid email address."
msgstr "ei ole kelvollinen sähköpostiosoite."

#: ../validators/BaseValidators.py:74
msgid "is not a valid international phone number."
msgstr "ei ole kelvollinen kansainvälinen puhelinnumero."

#: ../validators/BaseValidators.py:88
msgid "is not a valid url."
msgstr "ei ole kelvollinen url."

#: ../validators/BaseValidators.py:66
msgid "is not a valid us phone number."
msgstr "ei ole kelvollinen yhdysvaltojen puhelinnumero."

#: ../validators/BaseValidators.py:81
msgid "is not a valid zip code."
msgstr "ei ole kelvollinen postiosoite."

#: ../validators/BaseValidators.py:58
msgid "is not a well formed SSN."
msgstr "ei ole kelvollinen hetu."

#: ../validators/BaseValidators.py:44
msgid "is not an integer."
msgstr "ei ole kokonaisluku."

#: ../validators/BaseValidators.py:109
msgid "this name is not a valid identifier"
msgstr "tämä nimi ei ole kelvollinen tunniste"

#: ../validators/ExpressionValidator.py:94
msgid "validation failed, expr was:$expr"
msgstr "kelvollisuustarkistus epäonnistui, expr oli:$expr"
